devises views & more img
zekidok/perma-culture pull request #29
Opened 2019-03-13 13:04 UTC by xrxrxr

normalement no prob

2019-03-13 13:49 UTC, tclaudel requested changes
Met des link_to a la place des href et je te l'accepte :)

2019-03-13 15:26 UTC, xrxrxr reviewed
il en manque?

2019-03-14 08:40 UTC, deoladed approved these changes

2019-03-14 08:43 UTC, tclaudel approved these changes

2019-03-14 08:43 UTC, merged