Correction
zekidok/perma-culture pull request #55
Opened 2019-03-18 15:34 UTC by JulienTHP

2019-03-18 16:17 UTC, deoladed requested changes

2019-03-18 16:17 UTC, deoladed commented on app/controllers/users_controller.rb
> +	before_action only: [:show, :edit]
WTF ?

2019-03-18 16:17 UTC, deoladed commented on app/views/home/_sign_up.html.erb
> +                                    <img alt='icône' src=<%= image_path 'icone-logo.png' %>>
Allez au boulot, on veux des helper. Indice : image_tag 'icone-logo.png, alt:'Icone'

2019-03-18 16:27 UTC, JulienPelisson reviewed
Correction of the commit done

2019-03-19 08:18 UTC, deoladed approved these changes

2019-03-19 09:49 UTC, closed without merging